### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by rikki78** [mwittig/pimatic-denon-avr#17]
Hi,

I received this error and it asked to report it. So here it is...
```
error [pimatic]: A uncaught exception occured: Error: read ETIMEDOUT
    at exports._errnoException (util.js:870:11)
    at TCP.onread (net.js:552:26)
From connect
    at Socket.connect (/home/pi/pimatic-app/node_modules/pimatic/startup.coffee:55:29)
    at Agent.exports.connect.exports.createConnection (net.js:69:26)
    at Agent.createSocket (_http_agent.js:175:16)
    at Agent.addRequest (_http_agent.js:144:23)
    at new ClientRequest (_http_client.js:142:16)
    at Object.exports.request (http.js:31:10)
    at new Request (/home/pi/pimatic-app/node_modules/pimatic-denon-avr/node_modules/restler-promise/node_modules/restler-base/lib/restler.js:75:24)
    at request (/home/pi/pimatic-app/node_modules/pimatic-denon-avr/node_modules/restler-promise/node_modules/restler-base/lib/restler.js:327:17)
    at Object.get (/home/pi/pimatic-app/node_modules/pimatic-denon-avr/node_modules/restler-promise/node_modules/restler-base/lib/restler.js:334:9)
    at /home/pi/pimatic-app/node_modules/pimatic-denon-avr/node_modules/restler-promise/lib/restler-promise.js:28:38
    at Promise._execute (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/debuggability.js:299:9)
    at Promise._resolveFromExecutor (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:77:14)
    at Object.get (/home/pi/pimatic-app/node_modules/pimatic-denon-avr/node_modules/restler-promise/lib/restler-promise.js:27:20)
    at HttpAppProtocol._requestUpdate (/home/pi/pimatic-app/node_modules/pimatic-denon-avr/http-app-protocol.coffee:59:19)
    at HttpAppProtocol._requestUpdate (/home/pi/pimatic-app/node_modules/pimatic-denon-avr/http-app-protocol.coffee:2:1)
    at null._onTimeout (/home/pi/pimatic-app/node_modules/pimatic-denon-avr/node_modules/pimatic-plugin-commons/lib/index.js:218:27)
    at Timer.listOnTimeout (timers.js:92:15)
 This is most probably a bug in pimatic or in a module, please report it!

**Comment by mwittig** [comment]
Thanks for the report. Can you please provide some background info:

1) Which version of nodeJS do you use? ``` node --version```
2) Did the error occur more than once?
3) Is it reproduceable? For example, does it occur if the address is unreachable from the local network?

**Comment by rikki78** [comment]
1. v4.4.5
2. no
3. No, I have no idea what happened. If I remember correctly it happened at
night

Op di 7 feb. 2017 om 18:42 schreef Marcus Wittig <notifications@github.com>:

**Comment by mwittig** [comment]
Thanks. I have revised the error handling which should help to avoid unhandled errors.

**Comment by mwittig** [comment]
As the error wasn't reproducable for me it is hard to say whether or not the problem has been fixed now. Error handling has been improved though and some measures have been taken to isolate the connection handling from the global context. I am closing this issue now. Please file a new issue if the error occurs again.
