### ISSUE TITLE
Plugin not starting after latest update

### ISSUE THREAD

**Issue by thexperiments** [mwittig/pimatic-denon-avr#26]
```
13:49:05.163 [pimatic] info: Loading plugin: "pimatic-denon-avr" (0.9.8)
coffee-cache: compiling coffee-script file "denon-avr.coffee"...Done
coffee-cache: compiling coffee-script file "telnet-app-protocol.coffee"...Done
coffee-cache: compiling coffee-script file "http-app-protocol.coffee"...Done
13:49:07.283 [pimatic] error: Cannot find module './_assignValue'
13:49:07.318 [pimatic] debug: Error: Cannot find module './_assignValue'
13:49:07.318 [pimatic] debug:>    at Function.Module._resolveFilename (module.js:325:15)
13:49:07.318 [pimatic] debug:>    at Function.Module._load (module.js:276:25)
13:49:07.318 [pimatic] debug:>    at Module.require (module.js:353:17)
13:49:07.318 [pimatic] debug:>    at require (internal/module.js:12:17)
13:49:07.318 [pimatic] debug:>    at Object.<anonymous> (/home/pi/pimatic-beta/node_modules/pimatic-denon-avr/node_modules/xml2js/node_modules/xmlbuilder/node_modules/lodash/assign.js:1:19)
13:49:07.318 [pimatic] debug:>    at Module._compile (module.js:409:26)
13:49:07.318 [pimatic] debug:>    at Object.Module._extensions..js (module.js:416:10)
13:49:07.318 [pimatic] debug:>    at Module.load (/home/pi/pimatic-beta/node_modules/pimatic-mobile-frontend/node_modules/nap/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
13:49:07.318 [pimatic] debug:>    at Function.Module._load (module.js:300:12)
13:49:07.318 [pimatic] debug:>    at Module.require (module.js:353:17)
13:49:07.318 [pimatic] debug:>    at require (internal/module.js:12:17)
13:49:07.318 [pimatic] debug:>    at Object.<anonymous> (/home/pi/pimatic-beta/node_modules/pimatic-denon-avr/node_modules/xml2js/node_modules/xmlbuilder/lib/index.js:5:12)
13:49:07.318 [pimatic] debug:>    at Object.<anonymous> (/home/pi/pimatic-beta/node_modules/pimatic-denon-avr/node_modules/xml2js/node_modules/xmlbuilder/lib/index.js:14:4)
13:49:07.318 [pimatic] debug:>    at Module._compile (module.js:409:26)
13:49:07.318 [pimatic] debug:>    at Object.Module._extensions..js (module.js:416:10)
13:49:07.318 [pimatic] debug:>    at Module.load (/home/pi/pimatic-beta/node_modules/pimatic-mobile-frontend/node_modules/nap/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
13:49:07.318 [pimatic] debug:>    at Function.Module._load (module.js:300:12)
13:49:07.318 [pimatic] debug:>    at Module.require (module.js:353:17)
13:49:07.318 [pimatic] debug:>    at require (internal/module.js:12:17)
13:49:07.318 [pimatic] debug:>    at Object.<anonymous> (/home/pi/pimatic-beta/node_modules/pimatic-denon-avr/node_modules/xml2js/lib/xml2js.js:13:13)
13:49:07.318 [pimatic] debug:>    at Object.<anonymous> (/home/pi/pimatic-beta/node_modules/pimatic-denon-avr/node_modules/xml2js/lib/xml2js.js:543:4)
13:49:07.318 [pimatic] debug:>    at Module._compile (module.js:409:26)
13:49:07.318 [pimatic] debug:>    at Object.Module._extensions..js (module.js:416:10)
13:49:07.318 [pimatic] debug:>    at Module.load (/home/pi/pimatic-beta/node_modules/pimatic-mobile-frontend/node_modules/nap/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
13:49:07.318 [pimatic] debug:>    at Function.Module._load (module.js:300:12)
13:49:07.318 [pimatic] debug:>    at Module.require (module.js:353:17)
13:49:07.318 [pimatic] debug:>    at require (internal/module.js:12:17)
13:49:07.318 [pimatic] debug:>    at module.exports (/home/pi/pimatic-beta/node_modules/pimatic-denon-avr/http-app-protocol.coffee:7:38)
13:49:07.318 [pimatic] debug:>    at module.exports (/home/pi/pimatic-beta/node_modules/pimatic-denon-avr/denon-avr.coffee:7:21)
13:49:07.318 [pimatic] debug:>    at PluginManager.loadPlugin (/home/pi/pimatic-beta/node_modules/pimatic/lib/plugins.coffee:83:16)
13:49:07.318 [pimatic] debug:>    at /home/pi/pimatic-beta/node_modules/pimatic/lib/plugins.coffee:485:25
13:49:07.318 [pimatic] debug:>    at tryCatcher (/home/pi/pimatic-beta/node_modules/pimatic/node_modules/bluebird/js/release/util.js:16:23)
13:49:07.318 [pimatic] debug:>    at Promise._settlePromiseFromHandler (/home/pi/pimatic-beta/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:512:31)
13:49:07.318 [pimatic] debug:>    at Promise._settlePromise (/home/pi/pimatic-beta/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:569:18)
13:49:07.318 [pimatic] debug:>    at Promise._settlePromiseCtx (/home/pi/pimatic-beta/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:606:10)
13:49:07.318 [pimatic] debug:>    at Async._drainQueue (/home/pi/pimatic-beta/node_modules/pimatic/node_modules/bluebird/js/release/async.js:138:12)
13:49:07.318 [pimatic] debug:>    at Async._drainQueues (/home/pi/pimatic-beta/node_modules/pimatic/node_modules/bluebird/js/release/async.js:143:10)
13:49:07.318 [pimatic] debug:>    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/pimatic-beta/node_modules/pimatic/node_modules/bluebird/js/release/async.js:17:14)
13:49:07.318 [pimatic] debug:>    at processImmediate [as _immediateCallback] (timers.js:383:17)

```

**Comment by mwittig** [comment]
It looks like the update installation is incomplete. Maybe it is an issue with pimatic's update procedure. Can please check the log further back for suspects and report to pimatic/pimatic in case? This will be great. 

Try to remove the plugin dependencies and install them manually as follows:

```
sudo service pimatic stop
cd /home/pi/pimatic-beta/node_modules/pimatic-denon-avr
sudo rm -rf node_modules
sudo npm install -unsafe-perm
sudo service pimatic start
