### ISSUE TITLE
Unhandled exception if AVR is offline and network control is off

### ISSUE THREAD

**Issue by mwittig** [mwittig/pimatic-denon-avr#28]
If the Denon AVR is offline and you haven’t activated the option network control the following error occurs:

```
Unhandled rejection Error: Expected variable Denon-Volume-Status.volume to have a numeric value.
    at /home/pi/pimatic-app/node_modules/pimatic/lib/variables-ast-builder.coffee:111:17
    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
Unhandled rejection Error: unknown state=""!

**Comment by mwittig** [comment]
False alert. Device causing the exception is ShellSensor!

https://forum.pimatic.org/topic/1145/new-plugin-for-denon-marantz-avrs/27
